# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1374544302);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 10);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.showQuitWarning", true);
user_pref("browser.slowStartup.averageTime", 17494);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1374630701351");
user_pref("datareporting.policy.firstRunTime", "1374544301351");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 16);
user_pref("datareporting.sessions.current.startTime", "1374544366038");
user_pref("datareporting.sessions.current.totalTime", 2);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1374544252460,\"a\":6,\"t\":83,\"c\":true,\"m\":47993,\"fp\":50542,\"sr\":51304}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1374544348628,\"a\":4,\"t\":16,\"c\":true,\"m\":19,\"fp\":605,\"sr\":634}");
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-es-ES@firefox.mozilla.org\":{\"version\":\"22.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-ES@firefox.mozilla.org.xpi\"},\"langpack-zh-CN@firefox.mozilla.org\":{\"version\":\"22.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\"},\"langpack-es-AR@firefox.mozilla.org\":{\"version\":\"22.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-AR@firefox.mozilla.org.xpi\"},\"langpack-es-CL@firefox.mozilla.org\":{\"version\":\"22.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-CL@firefox.mozilla.org.xpi\"},\"langpack-es-MX@firefox.mozilla.org\":{\"version\":\"22.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-MX@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"22.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"22.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "mint-search-enhancer%40linuxmint.com:1.0,%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D:1.0.7,ubufox%40ubuntu.com:2.6,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:22.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1374077925000,\"rdfTime\":1352727066000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-es-ES@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-ES@firefox.mozilla.org.xpi\",\"mtime\":1372353554000},\"langpack-zh-CN@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"mtime\":1372353665000},\"langpack-es-AR@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-AR@firefox.mozilla.org.xpi\",\"mtime\":1372353554000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1374079595000,\"rdfTime\":1372352042000},\"langpack-es-CL@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-CL@firefox.mozilla.org.xpi\",\"mtime\":1372353554000},\"langpack-es-MX@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-es-MX@firefox.mozilla.org.xpi\",\"mtime\":1372353554000},\"mint-search-enhancer@linuxmint.com\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/mint-search-enhancer@linuxmint.com\",\"mtime\":1366902099000,\"rdfTime\":1336764609000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1372353549000},\"{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\",\"mtime\":1366902103000,\"rdfTime\":1336770080000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1372353549000}}}]");
user_pref("extensions.lastAppVersion", "22.0");
user_pref("extensions.lastPlatformVersion", "22.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130627161625");
user_pref("gecko.mstone", "22.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1374544366);
user_pref("toolkit.telemetry.previousBuildID", "20130627161625");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1377136305);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
